version: "3.7"
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: ${MDATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MUSER}
      MONGO_INITDB_ROOT_PASSWORD: ${MPASSWORD}
    ports:
      - "27019:27017"
    volumes:
      - lab6_data:/data/db
      # - ./mongo_init.sh:/docker-entrypoint-initdb.d/mongo_init.sh
  mongo-express:
    image: mongo-express
    ports:
      - 9081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MUSER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MPASSWORD}
    logging:
      driver: none
volumes:
  lab6_data:
